# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartlink/link.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smartlink/link.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14smartlink/link.proto\"\xa0\x02\n\x08NodeLink\x12\x10\n\x08nodeName\x18\x01 \x01(\t\x12\x10\n\x08nodeDesc\x18\x02 \x01(\t\x12 \n\x04type\x18\x03 \x01(\x0e\x32\x12.NodeLink.LinkType\x12%\n\x07\x64\x65vLink\x18\x04 \x03(\x0b\x32\x14.NodeLink.DeviceLink\x1a{\n\nDeviceLink\x12\x0f\n\x07\x64\x65vName\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65vDesc\x18\x02 \x01(\t\x12\'\n\x04link\x18\x03 \x03(\x0b\x32\x19.NodeLink.DeviceLink.Link\x1a\"\n\x04Link\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"*\n\x08LinkType\x12\r\n\tOPERATION\x10\x00\x12\x0f\n\x0b\x44\x45SCRIPTION\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_NODELINK_LINKTYPE = _descriptor.EnumDescriptor(
  name='LinkType',
  full_name='NodeLink.LinkType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPERATION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DESCRIPTION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=313,
)
_sym_db.RegisterEnumDescriptor(_NODELINK_LINKTYPE)


_NODELINK_DEVICELINK_LINK = _descriptor.Descriptor(
  name='Link',
  full_name='NodeLink.DeviceLink.Link',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NodeLink.DeviceLink.Link.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='NodeLink.DeviceLink.Link.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=269,
)

_NODELINK_DEVICELINK = _descriptor.Descriptor(
  name='DeviceLink',
  full_name='NodeLink.DeviceLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devName', full_name='NodeLink.DeviceLink.devName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devDesc', full_name='NodeLink.DeviceLink.devDesc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='link', full_name='NodeLink.DeviceLink.link', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NODELINK_DEVICELINK_LINK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=269,
)

_NODELINK = _descriptor.Descriptor(
  name='NodeLink',
  full_name='NodeLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeName', full_name='NodeLink.nodeName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeDesc', full_name='NodeLink.nodeDesc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='NodeLink.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devLink', full_name='NodeLink.devLink', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NODELINK_DEVICELINK, ],
  enum_types=[
    _NODELINK_LINKTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=313,
)

_NODELINK_DEVICELINK_LINK.containing_type = _NODELINK_DEVICELINK
_NODELINK_DEVICELINK.fields_by_name['link'].message_type = _NODELINK_DEVICELINK_LINK
_NODELINK_DEVICELINK.containing_type = _NODELINK
_NODELINK.fields_by_name['type'].enum_type = _NODELINK_LINKTYPE
_NODELINK.fields_by_name['devLink'].message_type = _NODELINK_DEVICELINK
_NODELINK_LINKTYPE.containing_type = _NODELINK
DESCRIPTOR.message_types_by_name['NodeLink'] = _NODELINK

NodeLink = _reflection.GeneratedProtocolMessageType('NodeLink', (_message.Message,), dict(

  DeviceLink = _reflection.GeneratedProtocolMessageType('DeviceLink', (_message.Message,), dict(

    Link = _reflection.GeneratedProtocolMessageType('Link', (_message.Message,), dict(
      DESCRIPTOR = _NODELINK_DEVICELINK_LINK,
      __module__ = 'smartlink.link_pb2'
      # @@protoc_insertion_point(class_scope:NodeLink.DeviceLink.Link)
      ))
    ,
    DESCRIPTOR = _NODELINK_DEVICELINK,
    __module__ = 'smartlink.link_pb2'
    # @@protoc_insertion_point(class_scope:NodeLink.DeviceLink)
    ))
  ,
  DESCRIPTOR = _NODELINK,
  __module__ = 'smartlink.link_pb2'
  # @@protoc_insertion_point(class_scope:NodeLink)
  ))
_sym_db.RegisterMessage(NodeLink)
_sym_db.RegisterMessage(NodeLink.DeviceLink)
_sym_db.RegisterMessage(NodeLink.DeviceLink.Link)


# @@protoc_insertion_point(module_scope)
