# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartlink.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smartlink.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fsmartlink.proto\"F\n\x0f\x44\x65viceOperation\x12\x12\n\ndevicename\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\"C\n\rNodeOperation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\noperations\x18\x02 \x03(\x0b\x32\x10.DeviceOperation\",\n\x0c\x44\x65viceUpdate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x03(\t\",\n\nNodeUpdate\x12\x1e\n\x07updates\x18\x01 \x03(\x0b\x32\r.DeviceUpdate\"2\n\x14OperationDescription\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"a\n\x11\x44\x65viceDescription\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12)\n\noperations\x18\x03 \x03(\x0b\x32\x15.OperationDescription\"Y\n\x0fNodeDescription\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12#\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\x12.DeviceDescriptionb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEVICEOPERATION = _descriptor.Descriptor(
  name='DeviceOperation',
  full_name='DeviceOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devicename', full_name='DeviceOperation.devicename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='DeviceOperation.operation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='DeviceOperation.args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=89,
)


_NODEOPERATION = _descriptor.Descriptor(
  name='NodeOperation',
  full_name='NodeOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NodeOperation.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operations', full_name='NodeOperation.operations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=158,
)


_DEVICEUPDATE = _descriptor.Descriptor(
  name='DeviceUpdate',
  full_name='DeviceUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DeviceUpdate.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='DeviceUpdate.status', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=204,
)


_NODEUPDATE = _descriptor.Descriptor(
  name='NodeUpdate',
  full_name='NodeUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='updates', full_name='NodeUpdate.updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=250,
)


_OPERATIONDESCRIPTION = _descriptor.Descriptor(
  name='OperationDescription',
  full_name='OperationDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='OperationDescription.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='OperationDescription.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=302,
)


_DEVICEDESCRIPTION = _descriptor.Descriptor(
  name='DeviceDescription',
  full_name='DeviceDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DeviceDescription.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='DeviceDescription.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operations', full_name='DeviceDescription.operations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=401,
)


_NODEDESCRIPTION = _descriptor.Descriptor(
  name='NodeDescription',
  full_name='NodeDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NodeDescription.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='NodeDescription.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devices', full_name='NodeDescription.devices', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=492,
)

_NODEOPERATION.fields_by_name['operations'].message_type = _DEVICEOPERATION
_NODEUPDATE.fields_by_name['updates'].message_type = _DEVICEUPDATE
_DEVICEDESCRIPTION.fields_by_name['operations'].message_type = _OPERATIONDESCRIPTION
_NODEDESCRIPTION.fields_by_name['devices'].message_type = _DEVICEDESCRIPTION
DESCRIPTOR.message_types_by_name['DeviceOperation'] = _DEVICEOPERATION
DESCRIPTOR.message_types_by_name['NodeOperation'] = _NODEOPERATION
DESCRIPTOR.message_types_by_name['DeviceUpdate'] = _DEVICEUPDATE
DESCRIPTOR.message_types_by_name['NodeUpdate'] = _NODEUPDATE
DESCRIPTOR.message_types_by_name['OperationDescription'] = _OPERATIONDESCRIPTION
DESCRIPTOR.message_types_by_name['DeviceDescription'] = _DEVICEDESCRIPTION
DESCRIPTOR.message_types_by_name['NodeDescription'] = _NODEDESCRIPTION

DeviceOperation = _reflection.GeneratedProtocolMessageType('DeviceOperation', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEOPERATION,
  __module__ = 'smartlink_pb2'
  # @@protoc_insertion_point(class_scope:DeviceOperation)
  ))
_sym_db.RegisterMessage(DeviceOperation)

NodeOperation = _reflection.GeneratedProtocolMessageType('NodeOperation', (_message.Message,), dict(
  DESCRIPTOR = _NODEOPERATION,
  __module__ = 'smartlink_pb2'
  # @@protoc_insertion_point(class_scope:NodeOperation)
  ))
_sym_db.RegisterMessage(NodeOperation)

DeviceUpdate = _reflection.GeneratedProtocolMessageType('DeviceUpdate', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEUPDATE,
  __module__ = 'smartlink_pb2'
  # @@protoc_insertion_point(class_scope:DeviceUpdate)
  ))
_sym_db.RegisterMessage(DeviceUpdate)

NodeUpdate = _reflection.GeneratedProtocolMessageType('NodeUpdate', (_message.Message,), dict(
  DESCRIPTOR = _NODEUPDATE,
  __module__ = 'smartlink_pb2'
  # @@protoc_insertion_point(class_scope:NodeUpdate)
  ))
_sym_db.RegisterMessage(NodeUpdate)

OperationDescription = _reflection.GeneratedProtocolMessageType('OperationDescription', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONDESCRIPTION,
  __module__ = 'smartlink_pb2'
  # @@protoc_insertion_point(class_scope:OperationDescription)
  ))
_sym_db.RegisterMessage(OperationDescription)

DeviceDescription = _reflection.GeneratedProtocolMessageType('DeviceDescription', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEDESCRIPTION,
  __module__ = 'smartlink_pb2'
  # @@protoc_insertion_point(class_scope:DeviceDescription)
  ))
_sym_db.RegisterMessage(DeviceDescription)

NodeDescription = _reflection.GeneratedProtocolMessageType('NodeDescription', (_message.Message,), dict(
  DESCRIPTOR = _NODEDESCRIPTION,
  __module__ = 'smartlink_pb2'
  # @@protoc_insertion_point(class_scope:NodeDescription)
  ))
_sym_db.RegisterMessage(NodeDescription)


# @@protoc_insertion_point(module_scope)
